analysis:
  checkpoints:
  - 0.0
  - 1.0
  plots:
    power_spectrum: true
    predictions: true
    training_loss: true
    w_dominant_irrep_fraction: true
data:
  batch_size: 128
  group_n: 5
  group_name: dihedral
  k: 2
  mode: exhaustive
  num_samples: 1000
  powers:
  - 0.0
  - 600.0
  - 200.0
  - 20.0
  seed: 10
  template_type: custom_fourier
device: cuda:1
model:
  hidden_dim: 200
  init_scale: 1.0e-07
  model_type: TwoLayerNet
  nonlinearity: square
  output_scale: 1.0
  return_all_outputs: false
  transform_type: quadratic
training:
  betas:
  - 0.9
  - 0.999
  degree: null
  epochs: 100000
  grad_clip: 0.1
  learning_rate: 0.002
  mode: offline
  num_steps: 100
  optimizer: per_neuron
  reduction_threshold: null
  save_param_interval: 1
  scaling_factor: -3
  verbose_interval: 400
  weight_decay: 0.0
